name = "ariady-putra/more_aiken_examples"
version = "1.9.0"
license = "Apache-2.0"
description = "Compatible with stdlib v1.9.0"

[repository]
user = "ariady-putra"
project = "more_aiken_examples"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"

[[dependencies]]
name = "aiken-extra/string_util"
version = "3.190.202405"
source = "github"

[[dependencies]]
name = "aiken-extra/time_util"
version = "5.190.202405"
source = "github"

[[dependencies]]
name = "aiken-extra/tx_util"
version = "1.190.202405"
source = "github"

[[dependencies]]
name = "ariady-putra/morbid"
version = "main"
source = "github"
